import bcrypt from 'bcrypt';
import bodyParser from 'body-parser';
import dotenv from 'dotenv';
import express from 'express';
import expressJwt from 'express-jwt';
import jwt from 'jsonwebtoken';
import prisma from './prisma/prisma.js';
import rentApi from './src/api/rent.js';
import userApi from './src/api/user.js';
import vehicleApi from './src/api/vehicle.js';
import consts from './src/consts/consts.js';
import Security from './src/security/security.js';
import cors from 'cors';
const security = new Security();
export { cors, rentApi, consts, expressJwt, bcrypt, jwt, vehicleApi, express, dotenv, prisma, security, userApi, bodyParser };
